# -*- coding: utf-8 -*-
"""weapon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adTickaU-JYVqUJ3MiZRYlcKmOThV8lB
"""

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

!rm -rf /content/drive/MyDrive/weapon_detection_final

from ultralytics import YOLO
import os
import glob
import cv2
import matplotlib.pyplot as plt

import zipfile

zip_path = '/content/drive/MyDrive/weapon_detection_final.zip'
extract_path = '/content/drive/MyDrive/'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

dataset_path = "/content/drive/MyDrive/weapon_detection_final"

for root, dirs, files in os.walk(dataset_path):
    print(root)

import glob
import os

dataset_path = "/content/drive/MyDrive/weapon_detection_final/"

def validate_split(split):
    img_path = f"{dataset_path}/{split}/images"
    lbl_path = f"{dataset_path}/{split}/labels"

    images = glob.glob(img_path + "/*.jpg")
    labels = glob.glob(lbl_path + "/*.txt")

    print(f"\n--- {split.upper()} ---")
    print("Images:", len(images))
    print("Labels:", len(labels))

    missing_labels = []
    for img in images:
        label = img.replace("images", "labels").replace(".jpg", ".txt")
        if not os.path.exists(label):
            missing_labels.append(img)

    print("Missing Labels:", len(missing_labels))

validate_split("train")
validate_split("valid")
validate_split("test")

import glob
import os

dataset_path = "/content/drive/MyDrive/weapon_detection_final/"

def check_empty_labels(split):
    lbl_path = f"{dataset_path}/{split}/labels"
    label_files = glob.glob(lbl_path + "/*.txt")

    empty = 0
    for file in label_files:
        if os.path.getsize(file) == 0:
            empty += 1

    print(f"{split} empty labels:", empty)

check_empty_labels("train")
check_empty_labels("valid")
check_empty_labels("test")

from collections import Counter
import glob

def class_distribution(split):
    lbl_path = f"{dataset_path}/{split}/labels"
    label_files = glob.glob(lbl_path + "/*.txt")

    classes = []

    for file in label_files:
        with open(file, 'r') as f:
            for line in f.readlines():
                cls = int(line.split()[0])
                classes.append(cls)

    print(f"\n{split} class distribution:")
    print(Counter(classes))

class_distribution("train")

with open(dataset_path + "/data.yaml") as f:
    print(f.read())

data_yaml_path = dataset_path + "/data.yaml"

content = """
train: /content/drive/MyDrive/weapon_detection_final/train/images
val: /content/drive/MyDrive/weapon_detection_final/valid/images
test: /content/drive/MyDrive/weapon_detection_final/test/images

nc: 11
names: ['Automatic_Rifle', 'Bazooka', 'Grenade_Launcher', 'Handgun', 'Knife', 'SMG', 'Shotgun', 'Sniper', 'Sword', 'Chef_Knife', 'Butcher_Knife']

roboflow:
  workspace: harshavardhan-adefc
  project: weapon-detection-ndkao
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/harshavardhan-adefc/weapon-detection-ndkao/dataset/1
"""

with open(data_yaml_path, "w") as f:
    f.write(content)

print("data.yaml updated successfully")

import cv2
import os
import matplotlib.pyplot as plt

img_dir = "/content/drive/MyDrive/weapon_detection_final/train/images"

# Take one sample image
img_file = os.listdir(img_dir)[0]
path = os.path.join(img_dir, img_file)

img = cv2.imread(path)
resized = cv2.resize(img, (640, 640))

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1,2,2)
plt.title("Resized Image (640x640)")
plt.imshow(cv2.cvtColor(resized, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.show()

import cv2
import matplotlib.pyplot as plt

img = cv2.imread("/content/drive/MyDrive/weapon_detection_final/train/images/" + os.listdir("/content/drive/MyDrive/weapon_detection_final/train/images")[0])

normalized = img / 255.0

print("Before normalization:", img[0][0])
print("After normalization:", normalized[0][0])

import cv2
import matplotlib.pyplot as plt

img_path = "/content/drive/MyDrive/weapon_detection_final/train/images/" + os.listdir("/content/drive/MyDrive/weapon_detection_final/train/images")[0]

img = cv2.imread(img_path)

# Applying Gaussian Blur (noise reduction)
denoised = cv2.GaussianBlur(img, (5,5), 0)

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1,2,2)
plt.title("After Noise Reduction")
plt.imshow(cv2.cvtColor(denoised, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.show()

import cv2
import matplotlib.pyplot as plt
import os

img_path = "/content/drive/MyDrive/weapon_detection_final/train/images/" + os.listdir("/content/drive/MyDrive/weapon_detection_final/train/images")[0]

img = cv2.imread(img_path)

# Convert to LAB color space
lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
l, a, b = cv2.split(lab)

# Apply CLAHE
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
cl = clahe.apply(l)

# Merge channels
limg = cv2.merge((cl, a, b))
enhanced = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)

# Display
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.title("Original")
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1,2,2)
plt.title("Contrast Enhanced")
plt.imshow(cv2.cvtColor(enhanced, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.show()

import cv2
import os
import glob
import random
from collections import Counter

img_dir = dataset_path + "/train/images"
lbl_dir = dataset_path + "/train/labels"

target_classes = [9, 10]
TARGET = 150

label_files = glob.glob(lbl_dir + "/*.txt")

# Get initial distribution
classes = []
for file in label_files:
    with open(file, 'r') as f:
        for line in f.readlines():
            classes.append(int(line.split()[0]))

dist = Counter(classes)
print("Before:", dist)

saved = 0

# LOOP until target reached
while any(dist[cls] < TARGET for cls in target_classes):

    for label_file in label_files:
        with open(label_file, 'r') as f:
            lines = f.readlines()

        class_ids = [int(line.split()[0]) for line in lines]

        if any(cls in target_classes for cls in class_ids):

            for cls in class_ids:
                if cls in target_classes and dist[cls] < TARGET:

                    base = os.path.splitext(os.path.basename(label_file))[0]

                    img_file = None
                    for ext in [".jpg", ".png", ".jpeg"]:
                        path = os.path.join(img_dir, base + ext)
                        if os.path.exists(path):
                            img_file = path
                            break

                    if img_file is None:
                        continue

                    img = cv2.imread(img_file)
                    aug_img = img.copy()

                    if random.random() < 0.5:
                        aug_img = cv2.flip(aug_img, 1)

                    value = random.randint(-30, 30)
                    aug_img = cv2.convertScaleAbs(aug_img, alpha=1, beta=value)

                    new_img = os.path.join(img_dir, f"aug_{saved}.jpg")
                    new_lbl = os.path.join(lbl_dir, f"aug_{saved}.txt")

                    cv2.imwrite(new_img, aug_img)

                    with open(new_lbl, 'w') as f:
                        f.writelines(lines)

                    saved += 1
                    dist[cls] += 1

                    if all(dist[c] >= TARGET for c in target_classes):
                        break

        if all(dist[c] >= TARGET for c in target_classes):
            break

print("After:", dist)
print("Augmentation done")

class_images = {
    0: "/content/drive/MyDrive/weapon_detection_final/train/images/Automatic-Rifle_66_jpeg.rf.669c7a4666b186b0168d40108d478a5c.jpg",
    1: "/content/drive/MyDrive/weapon_detection_final/train/images/Bazooka_32_jpeg.rf.25cc8bc1d1f022f003c3deeac1e6a464.jpg",
    2: "/content/drive/MyDrive/weapon_detection_final/train/images/Grenade-Launcher_76_jpeg.rf.7a4814860b143acf0035b18dc168ce78.jpg",
    3: "/content/drive/MyDrive/weapon_detection_final/train/images/Handgun_58_jpeg.rf.f684788a296b3976b9fcc73f3eac06a5.jpg",
    4: "/content/drive/MyDrive/weapon_detection_final/train/images/Knife_27_png.rf.6cb73176714a0b2e7d6d484202b43ddd.jpg",
    5: "/content/drive/MyDrive/weapon_detection_final/train/images/SMG_50_jpeg.rf.851e7ffa8bcdb45416cbefd889d0573b.jpg",
    6: "/content/drive/MyDrive/weapon_detection_final/train/images/Shotgun_25_jpeg.rf.5e27b8af257f8b55c923a7ec56171b29.jpg",
    7: "/content/drive/MyDrive/weapon_detection_final/train/images/Sniper_22_jpeg.rf.e89f02b33bc1c3934b9b6b6f1f52a619.jpg",
    8: "/content/drive/MyDrive/weapon_detection_final/train/images/Sword_55_jpeg.rf.ea4a6153b47c7fd042735bdffffaac63.jpg",
    9: "/content/drive/MyDrive/weapon_detection_final/train/images/chef_knife_8.jpg",
    10: "/content/drive/MyDrive/weapon_detection_final/train/images/butcher_knife_8.jpg"
}

import cv2
import matplotlib.pyplot as plt

names = ['Automatic Rifle', 'Bazooka', 'Grenade Launcher', 'Handgun', 'Knife',
         'SMG', 'Shotgun', 'Sniper', 'Sword', 'Chef Knife', 'Butcher Knife']

for cls, img_path in class_images.items():

    img = cv2.imread(img_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Edge detection
    edges = cv2.Canny(gray, 100, 200)

    # Contours
    _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    contour_img = img.copy()
    cv2.drawContours(contour_img, contours, -1, (0,255,0), 2)

    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.title(names[cls])
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.axis('off')

    plt.subplot(1,3,2)
    plt.title("Edges")
    plt.imshow(edges, cmap='gray')
    plt.axis('off')

    plt.subplot(1,3,3)
    plt.title("Contours")
    plt.imshow(cv2.cvtColor(contour_img, cv2.COLOR_BGR2RGB))
    plt.axis('off')

    plt.show()

from ultralytics import YOLO
model = YOLO("yolo12s.pt")

dataset_path = "/content/drive/MyDrive/weapon_detection_final"

results = model.train(
    data=dataset_path + "/data.yaml",
    epochs=120,
    imgsz=640,
    batch=8,
    device=0,

    optimizer="SGD",
    lr0=0.01,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,

    augment=True,
    degrees=10,
    translate=0.1,
    scale=0.5,
    shear=2.0,
    fliplr=0.5,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,

    patience=30,
    cache="disk",
    workers=4,
    amp=True
)
print("Training completed")

metrics = model.val()
print("Model Evaluation Metrics\n")

print(f"Accuracy: {metrics.box.map50}")
print(f"mAP@0.5:0.95: {metrics.box.map}")
print(f"Precision: {metrics.box.mp}")
print(f"Recall: {metrics.box.mr}")

!ls /content/runs/detect

from ultralytics import YOLO

best_model = YOLO("/content/runs/detect/train/weights/best.pt")

image_path = "/content/drive/MyDrive/weapon_detection_final/test/images/Automatic-Rifle_5_jpeg.rf.706d30c0d73d5894c8866fa911585e25.jpg"

results = best_model([image_path])
result = results[0]

weapon_rules = {
    "knife": {"lower": 0.40, "upper": 0.70, "threat": "LOW"},
    "chef knife": {"lower": 0.45, "upper": 0.75, "threat": "MEDIUM"},
    "butcher knife": {"lower": 0.50, "upper": 0.90, "threat": "VERY HIGH"},
    "revolver": {"lower": 0.55, "upper": 0.75, "threat": "HIGH"},
    "pistol": {"lower": 0.60, "upper": 0.85, "threat": "HIGH"},
    "sniper": {"lower": 0.70, "upper": 0.90, "threat": "HIGH"},
    "automatic rifle": {"lower": 0.60, "upper": 0.90, "threat": "VERY HIGH"},
    "smg": {"lower": 0.55, "upper": 0.85, "threat": "HIGH"},
    "shotgun": {"lower": 0.55, "upper": 0.85, "threat": "HIGH"},
    "handgun": {"lower": 0.55, "upper": 0.80, "threat": "HIGH"}
}

print("\nDetection Results with Threat Analysis\n")

total_risk = 0

for box in result.boxes:

    cls_id = int(box.cls[0])
    conf = float(box.conf[0])

    class_name = best_model.names[cls_id].lower()

    rule = weapon_rules.get(class_name)

    if rule:

        lower = rule["lower"]
        upper = rule["upper"]

        if conf < lower:
            threat = "Rejected Detection (Low Confidence)"

        elif lower <= conf <= upper:
            threat = rule["threat"]

        else:
            threat = "CRITICAL"

    else:
        # Default confidence-based threat classification

        if conf < 0.40:
            threat = "LOW"

        elif conf < 0.70:
            threat = "MEDIUM"

        else:
            threat = "HIGH"

    print("Weapon:", class_name)
    print("Confidence:", round(conf,3))
    print("Threat Level:", threat)

import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))

# Plot detection result with bounding boxes
plt.imshow(result.plot())

plt.title("Weapon Detection Result")
plt.axis("off")

import matplotlib.pyplot as plt
import cv2

cm_path = "/content/runs/detect/val/confusion_matrix.png"

img = cv2.imread(cm_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(8,8))
plt.imshow(img)
plt.title("Confusion Matrix")
plt.axis("off")

import pandas as pd

results = pd.read_csv("/content/runs/detect/train/results.csv")

results.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(results['epoch'], results['train/box_loss'], label='Box Loss')
plt.plot(results['epoch'], results['train/cls_loss'], label='Class Loss')
plt.plot(results['epoch'], results['train/dfl_loss'], label='DFL Loss')

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss Curves")
plt.legend()
plt.grid()

plt.show()

plt.figure(figsize=(6,5))

plt.scatter(results['metrics/precision(B)'], results['metrics/recall(B)'])

plt.xlabel("Precision")
plt.ylabel("Recall")
plt.title("Precision vs Recall Scatter Plot")

plt.show()

plt.figure(figsize=(6,5))

metric_data = [
    results['metrics/precision(B)'],
    results['metrics/recall(B)']
]

plt.boxplot(metric_data, labels=['Precision','Recall'])

plt.title("Evaluation Metrics Distribution")

plt.show()